services:

  postgres:
    
    image: postgres:alpine
    env_file:
      - ./secrets.env

  backend:

    build:
      args:
        build_env: production
      context: ./backend
      target: production
    command: ["scripts/wait_for_postgres.sh", "postgres"]
    depends_on:
      - postgres
    env_file:
      - ./secrets.env
    ports:
      - "8000:8000"

  webserver:
    
    build:
      context: ./frontend
      target: production
    depends_on:
      - backend
    ports:
      - "5001:80"
