"""initial

Revision ID: 167ad6748adf
Revises: 
Create Date: 2022-04-06 19:03:08.567618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167ad6748adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('host', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('guest_can_pause', sa.Boolean(), nullable=False),
    sa.Column('votes_to_skip', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_song', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('host'),
    sa.UniqueConstraint('code')
    )
    op.create_table('spotify_tokens',
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expiry_dt', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_table('vote',
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('room_code', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['room_code'], ['room.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('spotify_tokens')
    op.drop_table('room')
    # ### end Alembic commands ###
